defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
  persist_in_safe_mode: false # need to be false unless a bug with mongoid-tree will be fixed in mongoid.
  preload_models: true

development: &development
  <<: *defaults
  database: contentr_development

test:
  <<: *defaults
  database: contentr_test

production:
  <<: *development
